version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: gzacinema-client
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      # Nginx serve thẳng từ folder dist được SCP lên
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - gzacinema-net

networks:
  gzacinema-net:
    external: true
